### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rbrtmrtn**
First of all, `yalc` looks awesome! I'm looking forward to using it.

These are just some minor/stylistic edits to `README.md` I thought might be useful.

Thanks!

### CODE REVIEW

**Comment by whitecolor** [comment]
Thanks) I'm not sure about if nested headings of `Usage` block should be lowercase, I meant it was not just commands but actions shortcut.

**Comment by rbrtmrtn** [comment]
I see what you mean -- I went ahead and switched the Usage headings back :)

**Comment by whitecolor** [comment]
Ok, thanks for your work and attention)

**Comment by rbrtmrtn** [comment]
@whitecolor Likewise!

**Pull request merged**
