### PR TITLE
Make 'push' safe to use with watch scripts

### LINKED ISSUE #34: Watch scripts break on `yalc push`
## Problem
When running a watch script in a package consuming another local package that has been marked as a local dependency using yalc. When `yalc push` is called in the consumed package an error occurs and the watch script breaks in the consuming package.

Example of the error:
```
D:\repos\test-delete> yalc push
Pushing @test/test-delete@0.0.1 in D:\repos\test-delete-watcher
(node:31748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EPERM: operation not permitted, lstat 'D:\repos\test-delete-watcher\.yalc\@test\test-delete\lib\index.js'
(node:31748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Repo
Create two projects with the following files/contents
**test-delete**
- lib
  - `index.js`
- `package.json`
  ```
  {
      "name": "@test/test-delete",
      "version": "0.0.1",
      "main": "lib/index.js"
  }  
  ```

**test-delete-watcher**
- src
  - `index.js`
    ```
    require('@test/test-delete');
    ```
- `package.json`
  ```
  {
    "name": "@test/test-delete-watcher",
    "version": "0.0.0",
    "scripts": {
      "bundle": "webpack",
      "watch": "webpack --watch"
    },
    "dependencies": {
      "@test/test-delete": "file:../test-delete"
    },
    "devDependencies": {
      "webpack": "4.17.1",
      "webpack-command": "0.4.1"
    }
  }
  ```

in *test-delete-watcher* run `yarn install` (to get the webpack dependencies so that `yarn run bundle` and `yarn run watch` will work)

in *test-delete* run `yalc publish`

in *test-delete-watcher* run `yalc add @test/test-delete`

in *test-delete-watcher* run `yarn run watch` to start bundling and watching for changes

in *test-delete* run `yalc push`

See the failure above
Also in `test-delete-watcher/node_modules/@test/test-delete` the `src/index.js` file is now missing

To get the system to work again have to run `yalc push` in *test-delete* and restart the watch in *test-delete-watcher*

### System info
64-bit windows 10

### PR DESCRIPTION
**Pull request by greyepoxy**
This fixes #34

Same as https://github.com/whitecolor/yalc/pull/48 but only with required changes

### CODE REVIEW

**Comment by whitecolor** [comment]
Can you put `replaceContentsOfDirectory` method and all supplements into a separate file? That what I actually meant by a separate module.

**Comment by greyepoxy** [comment]
ahh I see, yeah sure

**Comment by greyepoxy** [comment]
Hmm I found some bugs with the mirror code will send some updates

**Comment by whitecolor** [comment]
why don't use `glob` to list all the files in dir? It will easily get a list of all files except `node_modules`.

My view on the algorithm:

- glob(source), make source files map `{fname: true}`
- glob(dest), make dest files map

- find dest files not in source, remove them
- for those that are in dest and source check if changed, if no change set `false` (or remove) in the source files map
- copy items that left in source files map {fname: true}

I understand that it is something that is done in your code, I just think this should take not so much code.

**Comment by greyepoxy** [comment]
sure I can try using glob

**Comment by greyepoxy** [comment]
Okay, I added tests for `mirrorDirectory` explicitly. 
As part of adding some corner case testing the logic had to become more robust. Also as part of that work I added support for symlinks (not sure if that is a scenario to expect or not) which further complicated things.

Looked into using globs instead of traversing the file system in `getAllItemsInDirectory` and found that it made the code more complicated because of the required conversion logic from the list of file paths to the file system tree structure (`DirectoryContents` in the code) I ended up needing in order to do the directory diffing logic properly.
The case that triggered the change to use a tree structure happens when a directory is converted into a symlinked directory and they both contain a file of the same name. In the old code the contained file would be deleted. With the new code (that compares each level of the directory structure) it does not delete the file contained in the symlinked directory correctly. If we don't want to support symlinks then I could revert this back to what it was and probably use globs successfully.

**Comment by greyepoxy** [comment]
Looks like watch scripts cause yalc to break in the case when we have to remove an item in order to replace it (directory to file for example). The sig file is written but an error is thrown by the fs-extra remove call, will see if I can fix it

**Comment by greyepoxy** [comment]
hmm well can't get it to repo...

**Comment by greyepoxy** [comment]
also answered my own question, when running `npm pack` (or doing `yalc publish`) symlinks are just ignored so I didn't need to add any support for them as they will never be copied to the yalc store. Will remove that support and try using globs again like we discussed

**Comment by greyepoxy** [comment]
Alright, I fixed all of the issues I was seeing and tried to address your feedback

The most annoying issue I saw was that at least on windows, completed calls to `fs.remove` or `fs.removeSync` do not mean that the file has actually been removed
On windows (maybe other platforms? Not sure...) if you remove a file/folder and then try and replace it with something else right away sometimes the file will not actually be deleted but instead put in a "PENDING DELETE" state. I was able to reliably reproduce this by having the watch script watching a file that I then replaced with a folder, seems to happen when other processes have a 'weak' references to a file/folder. The fix I added is to check if the file/folder was actually removed after the completed remove call and wait if it was not (an arbitrary 100 ms), if the file/folder still has not been removed then I log a (hopefully) useful error message. Should be a rare case as it should only occur when a file has been replaced with a folder (or a folder with a file) with the same name/path.

I also removed the logic related to symlinks since there is no need to support them here (`npm publish` ignores them as well as `yalc publish`)

Per your feedback I tried to convert to using globs again and it resulted in the code being more complex. The algorithm today compares each level of the source directory tree (with all of the file system operations being kicked off in parallel) which is difficult to do with globs since you only get the list of files back (not the directories). Going the approach of putting the file paths into a map (like I first did) results in in-efficient file operations in comparison to the current algorithm. Since more fs calls can make a pretty big difference on perceived performance of the mirror directory operation I am leaning towards how it is written. Let me know if you disagree, if you have any further suggestions happy to give them a try

Thanks for your time!

**Comment by OlegFilth** [comment]
guys, yalc pysh still break watch, is there any solution?) may be in future i'll do it, but now I need more practice

**Comment by darrencrossley** [comment]
@greyepoxy Thank you so so much - after many many hours of debugging our webpack configurations to allow inprogress code sharing between repos and many hours wasted with symlinks this appears to finally be a solution that works.

My only comment would be whether this should be the default behaviour or behind some kind of flag? I haven't run any performance checks but could imagine this approach to be more complex than a simple replace.

FWIW: tested on Ubuntu, all seems to work as expected. If this can be merged it would be awesome!

**Comment by greyepoxy** [comment]
Cool glad to hear it worked for you!

Yeah in theory (not that I measured it) it should be the same order of magnitude of file operations so would not expect it to be much different then the default behavior. Although with a significantly huge project, it might? I tested up to the thousands and it seemed fine.

**Comment by ffgregormueller** [comment]
Any chance for this to be merged some time soon?
Yalc is pretty awesome but it breaks from time to time because of the problem this PR would seemingly solve.

**Pull request closed without merging**
