### PR TITLE
add tslint hanging promise detection and fix errors

### PR DESCRIPTION
**Pull request by greyepoxy**
This removes the need for the tests to wait using a set timeout after calling any of the yalc functions. Also will help prevent any future subtle async bugs around timing

### CODE REVIEW

**Comment by greyepoxy** [comment]
hmm ci failure seems to be something weird. Looks like travis' artifactory endpoint is missing tslint?

**Comment by whitecolor** [comment]
I'm not sure what is going on, errors seems to be are about different packages, not `tslint`.

**Comment by greyepoxy** [comment]
okay let me see if I can kick travis to run again and see what happens then

**Comment by whitecolor** [comment]
I kicked it multiple times but it continues to produce the errors. You may try to make new PR and "debug" it =)

**Comment by greyepoxy** [comment]
hmm okay good to know, will give it a shot

**Comment by greyepoxy** [comment]
going to try recreating the pull request, see if that fixes the ci

**Pull request closed without merging**
